### ISSUE TITLE
使用 vuescrolljs 右侧有白线出现

### ISSUE THREAD

**Issue by cenjiaxiang** [YvesCoding/vuescrolljs#2]
![image](https://user-images.githubusercontent.com/17038259/42330307-77631500-80a5-11e8-9555-b239a11e8fb4.png)
已经不知道是什么问题，还想请教一下

**Comment by wangyi7099** [comment]
你好， 这是否跟你的css布局有关呢？ 请看一下。

**Comment by wangyi7099** [comment]
https://github.com/YvesCoding/vuescroll/issues/48

**Comment by wangyi7099** [comment]
try `4.7.1-rc.1`
