### ISSUE TITLE
为什么我使用slide之后就无法滚动了

### ISSUE THREAD

**Issue by freecodemans** [YvesCoding/vuescrolljs#4]
![image](https://user-images.githubusercontent.com/24969341/42413079-a55c27ce-824b-11e8-8c59-935237805a7a.png)

**Comment by freecodemans** [comment]
![image](https://user-images.githubusercontent.com/24969341/42413088-c76e517a-824b-11e8-9682-8c471296e18a.png)

**Comment by wangyi7099** [comment]
你好，slide模式偏向于手机端，在pc下需要用鼠标拖动完成滚动的，还有，请查看你的内容是否超出了容器呢？

**Comment by freecodemans** [comment]
![image](https://user-images.githubusercontent.com/24969341/42418096-c1f0313e-82cb-11e8-8b6c-8aae153222b9.png)
![image](https://user-images.githubusercontent.com/24969341/42418097-cf2530d4-82cb-11e8-9cab-f0c4c28eb125.png)
![image](https://user-images.githubusercontent.com/24969341/42418101-dbf390d0-82cb-11e8-8f7b-a97d9fe38444.png)
这样有问题吗

**Comment by freecodemans** [comment]
用鼠标是可以滚动，但在手机上是不能滚动，手机上要做上拉，和下拉，该怎么配置呢

**Comment by freecodemans** [comment]
![image](https://user-images.githubusercontent.com/24969341/42418152-08e80002-82cd-11e8-9fd7-a5974b9e2bb5.png)
上拉一直触发不了，下拉可以

**Comment by freecodemans** [comment]
移动端只能是slide模式，才能加载更多吗，而且容器必须的高度得是固定的吗，用到
![image](https://user-images.githubusercontent.com/24969341/42418228-70890ffc-82ce-11e8-8a9f-7915a829821f.png)
这样后就没问题了

**Comment by wangyi7099** [comment]
容器的高度必须是固定的， 否则不能判断是否内容超出了容器的高度， 也不能判断是否应该启用加载更多。 如果容器高度为百分比的话，或者不是一个px值， 可以将`sizeStrategy`设置为`number`让vuescroll自己判断容器的高度。像这样：
```javascript
     vuescroll: {
           sizeStrategy: 'number'
    }
```

**Comment by freecodemans** [comment]
请问将preventDefault设置为true后会带来什么不良的影响吗
![image](https://user-images.githubusercontent.com/24969341/42500924-1f40e668-8465-11e8-801f-ea5cc9d94826.png)

**Comment by freecodemans** [comment]
为false说错了

**Comment by wangyi7099** [comment]
当mode为slide的时候， 为了保证滚动的流畅性， 默认是阻止默认动作的（如移动端下用手点开a标签），如果设置为false的话就不阻止了。 但是点到a标签页面就会跳转。

**Comment by freecodemans** [comment]
在ios上为啥没能检测到内容的变化，在安卓上没问题

**Comment by freecodemans** [comment]
好急啊！期望作者能回复我

**Comment by freecodemans** [comment]
到处用refresh解了一下燃眉之急，希望作者给我回复

**Comment by wangyi7099** [comment]
我这mac上测试是正常的。。 手机端不知道啊 没有测试环境。。
