### ISSUE TITLE
vue-scroll外层用标签包起来的时候，滚动条不会出现

### ISSUE THREAD

**Issue by coderew** [YvesCoding/vuescrolljs#9]
`<div class="coupon-wrapper">
                <vue-scroll :ops="ops">
                        <coupon-item class="coupon" v-for="i in 10"></coupon-item>
                        <coupon-item class="coupon"></coupon-item>
                        <coupon-item class="coupon"></coupon-item>
                        <coupon-item class="coupon"></coupon-item>
                        <coupon-item class="coupon"></coupon-item>
                        <coupon-item class="coupon"></coupon-item>
                </vue-scroll>
            </div>`

如果讲vue-scroll放到<div class="coupon-wrapper">标签中包起来，则不会出现滚动条，去掉就可以

**Comment by wangyi7099** [comment]
最好的办法是给包裹的标签定高
